"""
=============================================================================
EduTrack – Multi-School Timetable & Attendance SaaS Platform
=============================================================================
Super Admin : /super/login          (manages all schools, generates codes)
School Admin: /login                (manages their school only)
Teacher scan: /scan/<token>         (mobile, no login needed)
=============================================================================
"""

from flask import (Flask, render_template, request, redirect,
                   url_for, jsonify, send_file, flash, session, abort)
import sqlite3, hashlib, secrets, string, csv, io, qrcode
from datetime import datetime, timedelta
from functools import wraps
from pathlib import Path

app = Flask(__name__)
app.secret_key = "edutrack_saas_2024_Xk9#mP2"

BASE_DIR  = Path(__file__).parent
DB_PATH   = BASE_DIR / "data" / "edutrack.db"
QR_BASE   = BASE_DIR / "static" / "qrcodes"
QR_BASE.mkdir(parents=True, exist_ok=True)
(BASE_DIR / "data").mkdir(parents=True, exist_ok=True)

GRACE_MINUTES     = 5
EARLY_OUT_MINUTES = 5
PLATFORM_NAME     = "EduTrack"
PLATFORM_URL      = "https://edutrack.onrender.com"   # update after deploy

# ── Context ───────────────────────────────────────────────────────────────────
@app.context_processor
def inject_globals():
    return {"now": datetime.now, "platform": PLATFORM_NAME}

# ── DB ────────────────────────────────────────────────────────────────────────
def get_db():
    conn = sqlite3.connect(str(DB_PATH))
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA foreign_keys=ON")
    return conn

def init_db():
    with get_db() as db:
        db.executescript("""
        -- Platform super admins (you)
        CREATE TABLE IF NOT EXISTS super_admins (
            id         INTEGER PRIMARY KEY AUTOINCREMENT,
            username   TEXT NOT NULL UNIQUE,
            password   TEXT NOT NULL,
            created_at TEXT DEFAULT (datetime('now','localtime'))
        );

        -- Schools
        CREATE TABLE IF NOT EXISTS schools (
            id           INTEGER PRIMARY KEY AUTOINCREMENT,
            name         TEXT NOT NULL,
            address      TEXT,
            province     TEXT,
            phone        TEXT,
            email        TEXT NOT NULL UNIQUE,
            principal    TEXT,
            logo_url     TEXT,
            status       TEXT DEFAULT 'pending',
            plan         TEXT DEFAULT 'trial',
            fee_waiver   INTEGER DEFAULT 0,
            waiver_reason TEXT,
            trial_ends   TEXT,
            plan_expires TEXT,
            access_code  TEXT UNIQUE,
            code_used    INTEGER DEFAULT 0,
            created_at   TEXT DEFAULT (datetime('now','localtime'))
        );

        -- School admins
        CREATE TABLE IF NOT EXISTS school_admins (
            id         INTEGER PRIMARY KEY AUTOINCREMENT,
            school_id  INTEGER NOT NULL REFERENCES schools(id),
            username   TEXT NOT NULL UNIQUE,
            password   TEXT NOT NULL,
            name       TEXT,
            email      TEXT,
            created_at TEXT DEFAULT (datetime('now','localtime'))
        );

        -- Access codes (generated by super admin)
        CREATE TABLE IF NOT EXISTS access_codes (
            id          INTEGER PRIMARY KEY AUTOINCREMENT,
            code        TEXT NOT NULL UNIQUE,
            plan        TEXT NOT NULL DEFAULT 'basic',
            months      INTEGER NOT NULL DEFAULT 12,
            fee_waiver  INTEGER DEFAULT 0,
            used        INTEGER DEFAULT 0,
            used_by     INTEGER REFERENCES schools(id),
            notes       TEXT,
            created_at  TEXT DEFAULT (datetime('now','localtime')),
            used_at     TEXT
        );

        -- Teachers (per school)
        CREATE TABLE IF NOT EXISTS teachers (
            id         INTEGER PRIMARY KEY AUTOINCREMENT,
            school_id  INTEGER NOT NULL REFERENCES schools(id),
            name       TEXT NOT NULL,
            surname    TEXT NOT NULL,
            initials   TEXT NOT NULL,
            phone      TEXT,
            email      TEXT,
            subjects   TEXT,
            active     INTEGER DEFAULT 1,
            created_at TEXT DEFAULT (datetime('now','localtime'))
        );

        -- Rooms (per school)
        CREATE TABLE IF NOT EXISTS rooms (
            id         INTEGER PRIMARY KEY AUTOINCREMENT,
            school_id  INTEGER NOT NULL REFERENCES schools(id),
            code       TEXT NOT NULL,
            name       TEXT NOT NULL,
            grade      TEXT,
            building   TEXT,
            qr_token   TEXT UNIQUE,
            created_at TEXT DEFAULT (datetime('now','localtime')),
            UNIQUE(school_id, code)
        );

        -- Periods (per school)
        CREATE TABLE IF NOT EXISTS periods (
            id         INTEGER PRIMARY KEY AUTOINCREMENT,
            school_id  INTEGER NOT NULL REFERENCES schools(id),
            name       TEXT NOT NULL,
            start_time TEXT NOT NULL,
            end_time   TEXT NOT NULL,
            is_break   INTEGER DEFAULT 0
        );

        -- Timetable (per school)
        CREATE TABLE IF NOT EXISTS timetable (
            id           INTEGER PRIMARY KEY AUTOINCREMENT,
            school_id    INTEGER NOT NULL REFERENCES schools(id),
            teacher_id   INTEGER NOT NULL REFERENCES teachers(id),
            room_id      INTEGER NOT NULL REFERENCES rooms(id),
            period_id    INTEGER NOT NULL REFERENCES periods(id),
            subject      TEXT NOT NULL,
            day_of_week  TEXT NOT NULL,
            week_type    TEXT DEFAULT 'ALL',
            -- Class/stream this slot belongs to (e.g. "10A", "11B")
            class_code   TEXT DEFAULT '',
            -- For splits: which student group goes here
            -- e.g. "Language A", "Language B", "Economics", "Life Sciences"
            -- Leave blank for unsplit whole-class slots
            split_group  TEXT DEFAULT '',
            -- Split type label for grouping on grid
            -- e.g. "Language Choice", "Science Choice", "Commerce Choice"
            split_label  TEXT DEFAULT '',
            -- Is this part of a split? 0=no, 1=yes
            is_split     INTEGER DEFAULT 0
        );

        -- Attendance (per school)
        CREATE TABLE IF NOT EXISTS attendance (
            id             INTEGER PRIMARY KEY AUTOINCREMENT,
            school_id      INTEGER NOT NULL REFERENCES schools(id),
            teacher_id     INTEGER NOT NULL REFERENCES teachers(id),
            room_id        INTEGER NOT NULL REFERENCES rooms(id),
            period_id      INTEGER REFERENCES periods(id),
            timetable_id   INTEGER,
            date           TEXT NOT NULL,
            day_of_week    TEXT NOT NULL,
            scan_in_time   TEXT NOT NULL,
            scan_out_time  TEXT,
            scheduled_start TEXT,
            scheduled_end  TEXT,
            in_status      TEXT NOT NULL DEFAULT 'ON_TIME',
            out_status     TEXT NOT NULL DEFAULT 'PRESENT',
            minutes_late   INTEGER DEFAULT 0,
            duration_mins  INTEGER,
            period_length  INTEGER,
            notes          TEXT,
            created_at     TEXT DEFAULT (datetime('now','localtime'))
        );
        """)

        # Default super admin
        pw = hashlib.sha256("edutrack2024".encode()).hexdigest()
        db.execute("INSERT OR IGNORE INTO super_admins(username,password) VALUES('superadmin',?)", (pw,))

        # ── Migration: add split columns to existing timetable tables ─────────
        existing = [r[1] for r in db.execute("PRAGMA table_info(timetable)").fetchall()]
        for col, defn in [
            ("class_code",  "TEXT DEFAULT ''"),
            ("split_group", "TEXT DEFAULT ''"),
            ("split_label", "TEXT DEFAULT ''"),
            ("is_split",    "INTEGER DEFAULT 0"),
        ]:
            if col not in existing:
                db.execute(f"ALTER TABLE timetable ADD COLUMN {col} {defn}")

        db.commit()

# ── Helpers ───────────────────────────────────────────────────────────────────
def _hash(pw):
    return hashlib.sha256(pw.encode()).hexdigest()

def _time_to_mins(t):
    h, m = map(int, t.split(":")); return h*60+m

def _generate_code(length=12):
    """Generate a readable access code like EDT-XXXX-XXXX-XXXX."""
    chars = string.ascii_uppercase + string.digits
    chars = chars.replace("0","").replace("O","").replace("I","").replace("1","")
    raw = "".join(secrets.choice(chars) for _ in range(length))
    return f"EDT-{raw[:4]}-{raw[4:8]}-{raw[8:12]}"

def _generate_qr(school_id, room_code, token):
    folder = QR_BASE / str(school_id)
    folder.mkdir(parents=True, exist_ok=True)
    url = f"{PLATFORM_URL}/scan/{token}"
    qr  = qrcode.QRCode(version=1,
                         error_correction=qrcode.constants.ERROR_CORRECT_H,
                         box_size=10, border=4)
    qr.add_data(url)
    qr.make(fit=True)
    img = qr.make_image(fill_color="#1a3c5e", back_color="white")
    img.save(str(folder / f"{room_code}.png"))

def _school_active(school):
    """Check if school subscription is active."""
    if school["status"] != "active":
        return False
    if school["fee_waiver"]:
        return True
    if school["plan_expires"]:
        exp = datetime.strptime(school["plan_expires"], "%Y-%m-%d")
        return exp >= datetime.now()
    return False

# ── Auth decorators ───────────────────────────────────────────────────────────
def super_required(f):
    @wraps(f)
    def decorated(*args, **kwargs):
        if not session.get("super_logged_in"):
            return redirect(url_for("super_login"))
        return f(*args, **kwargs)
    return decorated

def school_required(f):
    @wraps(f)
    def decorated(*args, **kwargs):
        if not session.get("school_logged_in"):
            return redirect(url_for("school_login"))
        return f(*args, **kwargs)
    return decorated

def get_current_school():
    with get_db() as db:
        return db.execute("SELECT * FROM schools WHERE id=?",
                          (session.get("school_id"),)).fetchone()

# =============================================================================
# PUBLIC PAGES
# =============================================================================

@app.route("/")
def landing():
    return render_template("landing.html")

@app.route("/register", methods=["GET","POST"])
def register():
    if request.method == "POST":
        email = request.form.get("email","").strip().lower()
        with get_db() as db:
            # Check email not already registered
            exists = db.execute("SELECT id FROM schools WHERE email=?", (email,)).fetchone()
            if exists:
                flash("This email is already registered. Please log in.", "error")
                return render_template("register.html")

            # Create school (pending until code activated)
            trial_ends = (datetime.now() + timedelta(days=30)).strftime("%Y-%m-%d")
            db.execute("""
                INSERT INTO schools(name,address,province,phone,email,principal,status,plan,trial_ends)
                VALUES(?,?,?,?,?,?,'trial','trial',?)
            """, (request.form["school_name"].strip(),
                  request.form.get("address","").strip(),
                  request.form.get("province","").strip(),
                  request.form.get("phone","").strip(),
                  email,
                  request.form.get("principal","").strip(),
                  trial_ends))
            school_id = db.execute("SELECT last_insert_rowid()").fetchone()[0]

            # Create school admin account
            admin_pw = _hash(request.form["password"])
            username = email.split("@")[0].replace(".","_")[:20]
            # Ensure unique username
            base = username
            i = 1
            while db.execute("SELECT id FROM school_admins WHERE username=?", (username,)).fetchone():
                username = f"{base}{i}"; i += 1

            db.execute("""
                INSERT INTO school_admins(school_id,username,password,name,email)
                VALUES(?,?,?,?,?)
            """, (school_id, username,
                  admin_pw,
                  request.form.get("contact_name","").strip(),
                  email))

            # Seed default periods
            for p in [
                ("Assembly","07:30","07:50",0),
                ("Period 1","07:50","08:30",0),
                ("Period 2","08:30","09:10",0),
                ("Period 3","09:10","09:50",0),
                ("Break","09:50","10:10",1),
                ("Period 4","10:10","10:50",0),
                ("Period 5","10:50","11:30",0),
                ("Period 6","11:30","12:10",0),
                ("Lunch","12:10","12:50",1),
                ("Period 7","12:50","13:30",0),
                ("Period 8","13:30","14:10",0),
            ]:
                db.execute("INSERT INTO periods(school_id,name,start_time,end_time,is_break) VALUES(?,?,?,?,?)",
                           (school_id,)+p)
            db.commit()

        flash(f"Account created! Your username is: {username}. You have 30 days free trial.", "success")
        return redirect(url_for("school_login"))
    return render_template("register.html")

@app.route("/apply-waiver", methods=["GET","POST"])
def apply_waiver():
    if request.method == "POST":
        with get_db() as db:
            school = db.execute("SELECT * FROM schools WHERE email=?",
                                (request.form["email"].strip().lower(),)).fetchone()
            if not school:
                flash("Email not found. Please register first.", "error")
                return render_template("apply_waiver.html")
            db.execute("""UPDATE schools SET fee_waiver=2, waiver_reason=? WHERE id=?""",
                       (request.form["reason"].strip(), school["id"]))
            db.commit()
        flash("Fee waiver application submitted. We will review and respond within 2 business days.", "success")
        return redirect(url_for("school_login"))
    return render_template("apply_waiver.html")

# =============================================================================
# SCHOOL ADMIN
# =============================================================================

@app.route("/login", methods=["GET","POST"])
def school_login():
    if request.method == "POST":
        username = request.form.get("username","").strip()
        pw       = _hash(request.form.get("password",""))
        with get_db() as db:
            admin = db.execute("""
                SELECT sa.*, s.name AS school_name, s.status AS school_status,
                       s.plan, s.plan_expires, s.fee_waiver, s.trial_ends, s.logo_url
                FROM school_admins sa
                JOIN schools s ON sa.school_id=s.id
                WHERE sa.username=? AND sa.password=?
            """, (username, pw)).fetchone()
        if admin:
            session["school_logged_in"] = True
            session["school_id"]        = admin["school_id"]
            session["school_name"]      = admin["school_name"]
            session["admin_name"]       = admin["name"] or username
            session["admin_username"]   = username
            return redirect(url_for("school_dashboard"))
        flash("Invalid username or password", "error")
    return render_template("school_login.html")

@app.route("/logout")
def school_logout():
    session.clear()
    return redirect(url_for("school_login"))

@app.route("/activate", methods=["GET","POST"])
@school_required
def activate():
    """School enters access code to activate/extend subscription."""
    if request.method == "POST":
        code = request.form.get("code","").strip().upper()
        sid  = session["school_id"]
        with get_db() as db:
            ac = db.execute("SELECT * FROM access_codes WHERE code=? AND used=0", (code,)).fetchone()
            if not ac:
                flash("Invalid or already used code. Please check the code and try again.", "error")
                return render_template("activate.html")

            # Calculate expiry
            months  = ac["months"]
            expires = (datetime.now() + timedelta(days=30*months)).strftime("%Y-%m-%d")

            # Update school
            db.execute("""UPDATE schools SET status='active', plan=?, plan_expires=?,
                          access_code=?, code_used=1,
                          fee_waiver=CASE WHEN ? THEN 1 ELSE fee_waiver END
                          WHERE id=?""",
                       (ac["plan"], expires, code,
                        ac["fee_waiver"], sid))

            # Mark code as used
            db.execute("""UPDATE access_codes SET used=1, used_by=?, used_at=?
                          WHERE id=?""",
                       (sid, datetime.now().strftime("%Y-%m-%d %H:%M"), ac["id"]))
            db.commit()

        session["school_status"] = "active"
        flash(f"✅ Activated! Your {ac['plan'].title()} plan is active until {expires}.", "success")
        return redirect(url_for("school_dashboard"))
    return render_template("activate.html")

@app.route("/dashboard")
@school_required
def school_dashboard():
    sid   = session["school_id"]
    today = datetime.now().strftime("%Y-%m-%d")
    dow   = datetime.now().strftime("%A").upper()[:3]
    with get_db() as db:
        school          = db.execute("SELECT * FROM schools WHERE id=?", (sid,)).fetchone()
        total_teachers  = db.execute("SELECT COUNT(*) FROM teachers WHERE school_id=? AND active=1", (sid,)).fetchone()[0]
        scheduled_today = db.execute("SELECT COUNT(*) FROM timetable WHERE school_id=? AND day_of_week=?", (sid,dow)).fetchone()[0]
        checkins_today  = db.execute("SELECT COUNT(*) FROM attendance WHERE school_id=? AND date=?", (sid,today)).fetchone()[0]
        late_today      = db.execute("SELECT COUNT(*) FROM attendance WHERE school_id=? AND date=? AND in_status='LATE'", (sid,today)).fetchone()[0]
        left_early      = db.execute("SELECT COUNT(*) FROM attendance WHERE school_id=? AND date=? AND out_status='LEFT_EARLY'", (sid,today)).fetchone()[0]
        no_checkout     = db.execute("SELECT COUNT(*) FROM attendance WHERE school_id=? AND date=? AND scan_out_time IS NULL", (sid,today)).fetchone()[0]
        avg_dur         = db.execute("SELECT ROUND(AVG(duration_mins),0) FROM attendance WHERE school_id=? AND date=? AND duration_mins IS NOT NULL", (sid,today)).fetchone()[0] or 0
        in_room         = db.execute("""
            SELECT a.*, t.name||' '||t.surname AS teacher_name, r.code AS room_code,
                   p.name AS period_name
            FROM attendance a
            JOIN teachers t ON a.teacher_id=t.id
            JOIN rooms r ON a.room_id=r.id
            LEFT JOIN periods p ON a.period_id=p.id
            WHERE a.school_id=? AND a.date=? AND a.scan_out_time IS NULL
            ORDER BY a.scan_in_time
        """, (sid,today)).fetchall()
        recent = db.execute("""
            SELECT a.*, t.name||' '||t.surname AS teacher_name, r.code AS room_code,
                   p.name AS period_name
            FROM attendance a
            JOIN teachers t ON a.teacher_id=t.id
            JOIN rooms r ON a.room_id=r.id
            LEFT JOIN periods p ON a.period_id=p.id
            WHERE a.school_id=? AND a.date=?
            ORDER BY COALESCE(a.scan_out_time,a.scan_in_time) DESC LIMIT 15
        """, (sid,today)).fetchall()
        missing = db.execute("""
            SELECT tt.*, t.name||' '||t.surname AS teacher_name,
                   r.code AS room_code, p.name AS period_name, p.start_time
            FROM timetable tt
            JOIN teachers t ON tt.teacher_id=t.id
            JOIN rooms r ON tt.room_id=r.id
            JOIN periods p ON tt.period_id=p.id
            WHERE tt.school_id=? AND tt.day_of_week=? AND p.is_break=0
              AND p.end_time <= ?
              AND NOT EXISTS (
                SELECT 1 FROM attendance a
                WHERE a.teacher_id=tt.teacher_id AND a.period_id=tt.period_id AND a.date=?
              )
            ORDER BY p.start_time
        """, (sid, dow, datetime.now().strftime("%H:%M"), today)).fetchall()

    return render_template("dashboard.html",
        school=school, total_teachers=total_teachers,
        scheduled_today=scheduled_today, checkins_today=checkins_today,
        late_today=late_today, left_early=left_early,
        no_checkout=no_checkout, avg_dur=avg_dur,
        in_room=in_room, recent=recent, missing=missing,
        today=today, dow=dow, school_active=_school_active(school))

# ── Teachers ──────────────────────────────────────────────────────────────────
@app.route("/teachers")
@school_required
def teachers():
    sid = session["school_id"]
    with get_db() as db:
        all_t = db.execute("SELECT * FROM teachers WHERE school_id=? ORDER BY surname,name", (sid,)).fetchall()
    return render_template("teachers.html", teachers=all_t)

@app.route("/teachers/add", methods=["POST"])
@school_required
def add_teacher():
    sid = session["school_id"]
    with get_db() as db:
        db.execute("INSERT INTO teachers(school_id,name,surname,initials,phone,email,subjects) VALUES(?,?,?,?,?,?,?)",
                   (sid, request.form["name"].strip(), request.form["surname"].strip(),
                    request.form["initials"].strip().upper(),
                    request.form.get("phone","").strip(), request.form.get("email","").strip(),
                    request.form.get("subjects","").strip()))
        db.commit()
    flash("Teacher added", "success")
    return redirect(url_for("teachers"))

@app.route("/teachers/edit/<int:tid>", methods=["POST"])
@school_required
def edit_teacher(tid):
    sid = session["school_id"]
    with get_db() as db:
        db.execute("""UPDATE teachers SET name=?,surname=?,initials=?,phone=?,email=?,subjects=?,active=?
                      WHERE id=? AND school_id=?""",
                   (request.form["name"].strip(), request.form["surname"].strip(),
                    request.form["initials"].strip().upper(),
                    request.form.get("phone","").strip(), request.form.get("email","").strip(),
                    request.form.get("subjects","").strip(),
                    int(request.form.get("active",1)), tid, sid))
        db.commit()
    flash("Teacher updated", "success")
    return redirect(url_for("teachers"))

@app.route("/teachers/delete/<int:tid>", methods=["POST"])
@school_required
def delete_teacher(tid):
    sid = session["school_id"]
    with get_db() as db:
        db.execute("UPDATE teachers SET active=0 WHERE id=? AND school_id=?", (tid, sid))
        db.commit()
    flash("Teacher deactivated", "success")
    return redirect(url_for("teachers"))

# ── Rooms ─────────────────────────────────────────────────────────────────────
@app.route("/rooms")
@school_required
def rooms():
    sid = session["school_id"]
    with get_db() as db:
        all_rooms = db.execute("SELECT * FROM rooms WHERE school_id=? ORDER BY code", (sid,)).fetchall()
    return render_template("rooms.html", rooms=all_rooms)

@app.route("/rooms/add", methods=["POST"])
@school_required
def add_room():
    sid   = session["school_id"]
    code  = request.form["code"].strip().upper()
    token = secrets.token_urlsafe(16)
    with get_db() as db:
        db.execute("INSERT INTO rooms(school_id,code,name,grade,building,qr_token) VALUES(?,?,?,?,?,?)",
                   (sid, code, request.form["name"].strip(),
                    request.form.get("grade","").strip(),
                    request.form.get("building","").strip(), token))
        db.commit()
    _generate_qr(sid, code, token)
    flash(f"Room {code} added and QR code generated", "success")
    return redirect(url_for("rooms"))

@app.route("/rooms/delete/<int:rid>", methods=["POST"])
@school_required
def delete_room(rid):
    sid = session["school_id"]
    with get_db() as db:
        db.execute("DELETE FROM rooms WHERE id=? AND school_id=?", (rid, sid))
        db.commit()
    flash("Room deleted", "success")
    return redirect(url_for("rooms"))

@app.route("/rooms/qr/<int:rid>")
@school_required
def download_qr(rid):
    sid = session["school_id"]
    with get_db() as db:
        room = db.execute("SELECT * FROM rooms WHERE id=? AND school_id=?", (rid, sid)).fetchone()
    if not room:
        abort(404)
    qr_path = QR_BASE / str(sid) / f"{room['code']}.png"
    if not qr_path.exists():
        _generate_qr(sid, room["code"], room["qr_token"])
    return send_file(str(qr_path), as_attachment=True,
                     download_name=f"QR_{room['code']}.png")

# ── Periods ───────────────────────────────────────────────────────────────────
@app.route("/periods")
@school_required
def periods():
    sid = session["school_id"]
    with get_db() as db:
        all_p = db.execute("SELECT * FROM periods WHERE school_id=? ORDER BY start_time", (sid,)).fetchall()
    return render_template("periods.html", periods=all_p)

@app.route("/periods/add", methods=["POST"])
@school_required
def add_period():
    sid = session["school_id"]
    with get_db() as db:
        db.execute("INSERT INTO periods(school_id,name,start_time,end_time,is_break) VALUES(?,?,?,?,?)",
                   (sid, request.form["name"].strip(), request.form["start_time"],
                    request.form["end_time"], 1 if request.form.get("is_break") else 0))
        db.commit()
    flash("Period added", "success")
    return redirect(url_for("periods"))

@app.route("/periods/delete/<int:pid>", methods=["POST"])
@school_required
def delete_period(pid):
    sid = session["school_id"]
    with get_db() as db:
        db.execute("DELETE FROM periods WHERE id=? AND school_id=?", (pid, sid))
        db.commit()
    flash("Period deleted", "success")
    return redirect(url_for("periods"))

# ── Timetable ─────────────────────────────────────────────────────────────────
@app.route("/timetable")
@school_required
def timetable():
    sid = session["school_id"]
    with get_db() as db:
        tch   = db.execute("SELECT * FROM teachers WHERE school_id=? AND active=1 ORDER BY surname", (sid,)).fetchall()
        rms   = db.execute("SELECT * FROM rooms WHERE school_id=? ORDER BY code", (sid,)).fetchall()
        prds  = db.execute("SELECT * FROM periods WHERE school_id=? ORDER BY start_time", (sid,)).fetchall()
        slots = db.execute("""
            SELECT tt.*, t.name||' '||t.surname AS teacher_name, t.initials,
                   r.code AS room_code, p.name AS period_name,
                   p.start_time, p.end_time
            FROM timetable tt
            JOIN teachers t ON tt.teacher_id=t.id
            JOIN rooms r    ON tt.room_id=r.id
            JOIN periods p  ON tt.period_id=p.id
            WHERE tt.school_id=?
            ORDER BY tt.day_of_week, p.start_time, r.code
        """, (sid,)).fetchall()
    return render_template("timetable.html", teachers=tch, rooms=rms,
                           periods=prds, slots=slots,
                           days=["MON","TUE","WED","THU","FRI"])

@app.route("/timetable/add", methods=["POST"])
@school_required
def add_slot():
    sid         = session["school_id"]
    teacher_id  = request.form["teacher_id"]
    room_id     = request.form["room_id"]
    period_id   = request.form["period_id"]
    subject     = request.form["subject"].strip()
    dow         = request.form["day_of_week"].upper()
    week_type   = request.form.get("week_type","ALL")
    class_code  = request.form.get("class_code","").strip().upper()
    is_split    = 1 if request.form.get("is_split") else 0
    split_group = request.form.get("split_group","").strip()  # e.g. "IsiZulu Group"
    split_label = request.form.get("split_label","").strip()  # e.g. "Language Choice"

    with get_db() as db:
        # ── Clash 1: Teacher in two places at the same time ──────────────────
        # This is ALWAYS a clash — even in splits a teacher can only be in one room
        teacher_clash = db.execute("""
            SELECT tt.*, r.code AS room_code, p.name AS period_name
            FROM timetable tt
            JOIN rooms r   ON tt.room_id=r.id
            JOIN periods p ON tt.period_id=p.id
            WHERE tt.school_id=? AND tt.teacher_id=?
              AND tt.period_id=? AND tt.day_of_week=?
              AND (tt.week_type='ALL' OR ?='ALL' OR tt.week_type=?)
              AND tt.room_id != ?
        """, (sid, teacher_id, period_id, dow,
              week_type, week_type, room_id)).fetchone()

        if teacher_clash:
            t = db.execute("SELECT name,surname FROM teachers WHERE id=?",
                           (teacher_id,)).fetchone()
            flash(f"⛔ TEACHER CLASH: {t['name']} {t['surname']} is already "
                  f"assigned to room {teacher_clash['room_code']} during "
                  f"{teacher_clash['period_name']} on {dow}. "
                  f"A teacher cannot be in two places at once.", "error")
            return redirect(url_for("timetable"))

        # ── Clash 2: Room occupied — but only if NOT a legitimate split ───────
        # A room clash is real only when:
        #   - It's not a split at all, OR
        #   - Both slots are splits but with the same split_group in the same room
        # A room clash is NOT real when:
        #   - Both entries are splits of the same class to different rooms
        #     (e.g. 10A Language A → Zulu Lab, 10A Language B → Sesotho Room)
        room_existing = db.execute("""
            SELECT tt.*, t.name||' '||t.surname AS teacher_name,
                   t.id AS tid
            FROM timetable tt
            JOIN teachers t ON tt.teacher_id=t.id
            WHERE tt.school_id=? AND tt.room_id=?
              AND tt.period_id=? AND tt.day_of_week=?
              AND (tt.week_type='ALL' OR ?='ALL' OR tt.week_type=?)
              AND tt.teacher_id != ?
        """, (sid, room_id, period_id, dow,
              week_type, week_type, teacher_id)).fetchone()

        if room_existing:
            # Determine if this is a legitimate split or a real clash
            # Legitimate: both are splits AND they belong to different split_groups
            both_splits    = is_split and room_existing["is_split"]
            diff_groups    = split_group and room_existing["split_group"] and \
                             split_group != room_existing["split_group"]
            legit_split    = both_splits and diff_groups

            if not legit_split:
                r = db.execute("SELECT code FROM rooms WHERE id=?", (room_id,)).fetchone()
                flash(f"⛔ ROOM CLASH: Room {r['code']} is already occupied by "
                      f"{room_existing['teacher_name']} during this period on {dow}. "
                      f"If this is a class split (e.g. Language groups), "
                      f"tick 'This is a split class' and enter a split group name.", "error")
                return redirect(url_for("timetable"))

        # ── Clash 3: Exact duplicate ──────────────────────────────────────────
        duplicate = db.execute("""
            SELECT id FROM timetable
            WHERE school_id=? AND teacher_id=? AND room_id=?
              AND period_id=? AND day_of_week=?
        """, (sid, teacher_id, room_id, period_id, dow)).fetchone()

        if duplicate:
            flash("⚠️ This exact slot already exists in the timetable.", "error")
            return redirect(url_for("timetable"))

        # ── All clear — save ──────────────────────────────────────────────────
        try:
            db.execute("""
                INSERT INTO timetable
                (school_id,teacher_id,room_id,period_id,subject,
                 day_of_week,week_type,class_code,is_split,split_group,split_label)
                VALUES(?,?,?,?,?,?,?,?,?,?,?)
            """, (sid, teacher_id, room_id, period_id, subject,
                  dow, week_type, class_code, is_split,
                  split_group, split_label))
            db.commit()

            if is_split:
                flash(f"✅ Split slot added — {split_group or subject} "
                      f"({split_label or 'Split class'})", "success")
            else:
                flash("✅ Slot added successfully.", "success")
        except Exception as e:
            flash(f"Error saving slot: {e}", "error")

    return redirect(url_for("timetable"))


@app.route("/timetable/clashes")
@school_required
def check_clashes():
    """Full timetable analysis — clashes, splits, overloads."""
    sid = session["school_id"]
    with get_db() as db:
        # ── Real teacher clashes (same teacher, same period, different rooms) ─
        teacher_clashes = db.execute("""
            SELECT tt.teacher_id, tt.period_id, tt.day_of_week,
                   t.name||' '||t.surname AS teacher_name,
                   p.name AS period_name, p.start_time,
                   GROUP_CONCAT(r.code, ' & ') AS rooms,
                   COUNT(*) AS clash_count
            FROM timetable tt
            JOIN teachers t ON tt.teacher_id=t.id
            JOIN rooms r    ON tt.room_id=r.id
            JOIN periods p  ON tt.period_id=p.id
            WHERE tt.school_id=?
            GROUP BY tt.teacher_id, tt.period_id, tt.day_of_week
            HAVING COUNT(DISTINCT tt.room_id) > 1
            ORDER BY tt.day_of_week, p.start_time
        """, (sid,)).fetchall()

        # ── Real room clashes (same room, same period, different teachers,
        #    but NOT legitimate splits with different group labels) ─────────────
        room_clashes = db.execute("""
            SELECT tt.room_id, tt.period_id, tt.day_of_week,
                   r.code AS room_code,
                   p.name AS period_name, p.start_time,
                   GROUP_CONCAT(t.name||' '||t.surname, ' & ') AS teachers,
                   COUNT(*) AS clash_count,
                   SUM(tt.is_split) AS split_count,
                   COUNT(DISTINCT NULLIF(tt.split_group,'')) AS distinct_groups
            FROM timetable tt
            JOIN rooms r    ON tt.room_id=r.id
            JOIN teachers t ON tt.teacher_id=t.id
            JOIN periods p  ON tt.period_id=p.id
            WHERE tt.school_id=?
            GROUP BY tt.room_id, tt.period_id, tt.day_of_week
            HAVING COUNT(DISTINCT tt.teacher_id) > 1
              -- Only flag if NOT all entries are splits with distinct groups
              AND NOT (
                COUNT(*) = SUM(tt.is_split)
                AND COUNT(DISTINCT NULLIF(tt.split_group,'')) = COUNT(*)
              )
            ORDER BY tt.day_of_week, p.start_time
        """, (sid,)).fetchall()

        # ── Split summary (informational — not a clash) ───────────────────────
        splits_summary = db.execute("""
            SELECT tt.class_code, tt.split_label, tt.period_id,
                   tt.day_of_week, p.name AS period_name, p.start_time,
                   COUNT(*) AS group_count,
                   GROUP_CONCAT(tt.split_group||' ('||r.code||')', ' | ') AS groups
            FROM timetable tt
            JOIN periods p ON tt.period_id=p.id
            JOIN rooms r   ON tt.room_id=r.id
            WHERE tt.school_id=? AND tt.is_split=1 AND tt.class_code != ''
            GROUP BY tt.class_code, tt.split_label, tt.period_id, tt.day_of_week
            ORDER BY tt.class_code, tt.day_of_week, p.start_time
        """, (sid,)).fetchall()

        # ── Overloaded teachers ───────────────────────────────────────────────
        overloaded = db.execute("""
            SELECT t.id, t.name||' '||t.surname AS teacher_name,
                   COUNT(*) AS total_slots
            FROM timetable tt JOIN teachers t ON tt.teacher_id=t.id
            WHERE tt.school_id=?
            GROUP BY t.id HAVING COUNT(*) > 40
            ORDER BY total_slots DESC
        """, (sid,)).fetchall()

        # ── Unassigned teachers ───────────────────────────────────────────────
        unassigned = db.execute("""
            SELECT t.name||' '||t.surname AS teacher_name
            FROM teachers t
            WHERE t.school_id=? AND t.active=1
              AND NOT EXISTS (
                SELECT 1 FROM timetable tt
                WHERE tt.teacher_id=t.id AND tt.school_id=?
              )
            ORDER BY t.surname
        """, (sid, sid)).fetchall()

        total_slots   = db.execute(
            "SELECT COUNT(*) FROM timetable WHERE school_id=?", (sid,)).fetchone()[0]
        total_splits  = db.execute(
            "SELECT COUNT(*) FROM timetable WHERE school_id=? AND is_split=1", (sid,)).fetchone()[0]

    total_clashes = len(teacher_clashes) + len(room_clashes)
    return render_template("clashes.html",
        teacher_clashes=teacher_clashes, room_clashes=room_clashes,
        splits_summary=splits_summary,
        overloaded=overloaded, unassigned=unassigned,
        total_clashes=total_clashes,
        total_slots=total_slots, total_splits=total_splits)

@app.route("/timetable/delete/<int:sid_>", methods=["POST"])
@school_required
def delete_slot(sid_):
    sid = session["school_id"]
    with get_db() as db:
        db.execute("DELETE FROM timetable WHERE id=? AND school_id=?", (sid_, sid))
        db.commit()
    flash("Slot removed", "success")
    return redirect(url_for("timetable"))

@app.route("/timetable/view")
@school_required
def timetable_view():
    sid = session["school_id"]
    with get_db() as db:
        rooms   = db.execute("SELECT * FROM rooms WHERE school_id=? ORDER BY code", (sid,)).fetchall()
        periods = db.execute("SELECT * FROM periods WHERE school_id=? ORDER BY start_time", (sid,)).fetchall()
        slots   = db.execute("""
            SELECT tt.*, t.name||' '||t.surname AS teacher_name, t.initials,
                   r.code AS room_code, p.name AS period_name, p.start_time, p.end_time
            FROM timetable tt
            JOIN teachers t ON tt.teacher_id=t.id
            JOIN rooms r    ON tt.room_id=r.id
            JOIN periods p  ON tt.period_id=p.id
            WHERE tt.school_id=?
        """, (sid,)).fetchall()
    days = ["MON","TUE","WED","THU","FRI"]
    grid = {d: {p["id"]: {} for p in periods} for d in days}
    for s in slots:
        d, pid, rc = s["day_of_week"], s["period_id"], s["room_code"]
        if d in grid and pid in grid[d]:
            grid[d][pid][rc] = dict(s)
    return render_template("timetable_view.html",
                           grid=grid, days=days, rooms=rooms, periods=periods)

# ── Attendance ────────────────────────────────────────────────────────────────
@app.route("/attendance")
@school_required
def attendance():
    sid       = session["school_id"]
    today     = datetime.now().strftime("%Y-%m-%d")
    date_from = request.args.get("date_from", today)
    date_to   = request.args.get("date_to",   today)
    t_filter  = request.args.get("teacher_id","")
    s_filter  = request.args.get("in_status","")
    o_filter  = request.args.get("out_status","")

    q = """SELECT a.*, t.name||' '||t.surname AS teacher_name,
                  r.code AS room_code, p.name AS period_name
           FROM attendance a
           JOIN teachers t ON a.teacher_id=t.id
           JOIN rooms r    ON a.room_id=r.id
           LEFT JOIN periods p ON a.period_id=p.id
           WHERE a.school_id=? AND a.date BETWEEN ? AND ?"""
    params = [sid, date_from, date_to]
    if t_filter: q += " AND a.teacher_id=?"; params.append(t_filter)
    if s_filter: q += " AND a.in_status=?";  params.append(s_filter)
    if o_filter: q += " AND a.out_status=?"; params.append(o_filter)
    q += " ORDER BY a.date DESC, a.scan_in_time DESC"

    with get_db() as db:
        records  = db.execute(q, params).fetchall()
        teachers = db.execute("SELECT * FROM teachers WHERE school_id=? AND active=1 ORDER BY surname", (sid,)).fetchall()
        total    = len(records)
        on_time  = sum(1 for r in records if r["in_status"]=="ON_TIME")
        late     = sum(1 for r in records if r["in_status"]=="LATE")
        left_early = sum(1 for r in records if r["out_status"]=="LEFT_EARLY")
        no_out   = sum(1 for r in records if not r["scan_out_time"])
        durs     = [r["duration_mins"] for r in records if r["duration_mins"]]
        avg_dur  = round(sum(durs)/len(durs),0) if durs else 0

        teacher_stats = db.execute("""
            SELECT t.id, t.name||' '||t.surname AS teacher_name,
                   COUNT(*) AS total,
                   SUM(CASE WHEN a.in_status='ON_TIME' THEN 1 ELSE 0 END) AS on_time,
                   SUM(CASE WHEN a.in_status='LATE'    THEN 1 ELSE 0 END) AS late,
                   SUM(CASE WHEN a.out_status='LEFT_EARLY' THEN 1 ELSE 0 END) AS left_early,
                   ROUND(AVG(a.duration_mins),0) AS avg_duration,
                   SUM(CASE WHEN a.in_status='LATE' THEN a.minutes_late ELSE 0 END) AS total_late_mins
            FROM attendance a JOIN teachers t ON a.teacher_id=t.id
            WHERE a.school_id=? AND a.date BETWEEN ? AND ?
            GROUP BY t.id ORDER BY late DESC
        """, (sid, date_from, date_to)).fetchall()

    return render_template("attendance.html",
        records=records, teachers=teachers, teacher_stats=teacher_stats,
        total=total, on_time=on_time, late=late,
        left_early=left_early, no_out=no_out, avg_dur=avg_dur,
        date_from=date_from, date_to=date_to,
        t_filter=t_filter, s_filter=s_filter, o_filter=o_filter)

@app.route("/attendance/export")
@school_required
def export_attendance():
    sid       = session["school_id"]
    date_from = request.args.get("date_from", datetime.now().strftime("%Y-%m-01"))
    date_to   = request.args.get("date_to",   datetime.now().strftime("%Y-%m-%d"))
    with get_db() as db:
        rows = db.execute("""
            SELECT a.date, a.day_of_week, t.name||' '||t.surname AS teacher,
                   r.code AS room, p.name AS period,
                   a.scan_in_time, a.scan_out_time, a.scheduled_start, a.scheduled_end,
                   a.in_status, a.out_status, a.minutes_late, a.duration_mins, a.period_length
            FROM attendance a
            JOIN teachers t ON a.teacher_id=t.id
            JOIN rooms r ON a.room_id=r.id
            LEFT JOIN periods p ON a.period_id=p.id
            WHERE a.school_id=? AND a.date BETWEEN ? AND ?
            ORDER BY a.date, a.scan_in_time
        """, (sid, date_from, date_to)).fetchall()
    out = io.StringIO()
    w = csv.writer(out)
    w.writerow(["Date","Day","Teacher","Room","Period","Check In","Check Out",
                "Sched Start","Sched End","In Status","Out Status",
                "Mins Late","Duration (min)","Period Length"])
    for r in rows: w.writerow(list(r))
    out.seek(0)
    school_name = session.get("school_name","school").replace(" ","_")
    return send_file(io.BytesIO(out.getvalue().encode()), mimetype="text/csv",
                     as_attachment=True,
                     download_name=f"{school_name}_attendance_{date_from}_to_{date_to}.csv")

@app.route("/attendance/delete/<int:aid>", methods=["POST"])
@school_required
def delete_attendance(aid):
    sid = session["school_id"]
    with get_db() as db:
        db.execute("DELETE FROM attendance WHERE id=? AND school_id=?", (aid, sid))
        db.commit()
    flash("Record deleted", "success")
    return redirect(url_for("attendance"))

@app.route("/attendance/manual_out/<int:aid>", methods=["POST"])
@school_required
def manual_checkout(aid):
    sid = session["school_id"]
    with get_db() as db:
        rec = db.execute("SELECT * FROM attendance WHERE id=? AND school_id=?", (aid, sid)).fetchone()
        if rec and not rec["scan_out_time"]:
            t   = request.form.get("checkout_time", datetime.now().strftime("%H:%M"))
            dur = _time_to_mins(t) - _time_to_mins(rec["scan_in_time"])
            db.execute("UPDATE attendance SET scan_out_time=?,duration_mins=?,out_status='COMPLETED' WHERE id=?",
                       (t, dur, aid))
            db.commit()
            flash("Checked out manually", "success")
    return redirect(url_for("attendance"))

# ── Settings ──────────────────────────────────────────────────────────────────
@app.route("/settings", methods=["GET","POST"])
@school_required
def school_settings():
    sid = session["school_id"]
    with get_db() as db:
        school = db.execute("SELECT * FROM schools WHERE id=?", (sid,)).fetchone()
    if request.method == "POST":
        with get_db() as db:
            db.execute("""UPDATE schools SET name=?,address=?,province=?,phone=?,principal=?,logo_url=?
                          WHERE id=?""",
                       (request.form["school_name"].strip(),
                        request.form.get("address","").strip(),
                        request.form.get("province","").strip(),
                        request.form.get("phone","").strip(),
                        request.form.get("principal","").strip(),
                        request.form.get("logo_url","").strip(), sid))
            # Update server URL → regenerate QR codes
            new_url = request.form.get("server_url","").strip()
            if new_url:
                global PLATFORM_URL
                PLATFORM_URL = new_url
                rooms = db.execute("SELECT * FROM rooms WHERE school_id=?", (sid,)).fetchall()
                for room in rooms:
                    _generate_qr(sid, room["code"], room["qr_token"])
            db.commit()
        session["school_name"] = request.form["school_name"].strip()
        flash("Settings saved", "success")
        return redirect(url_for("school_settings"))
    return render_template("school_settings.html", school=school,
                           server_url=PLATFORM_URL)

# =============================================================================
# QR SCAN (teacher-facing, no login)
# =============================================================================

@app.route("/scan/<token>")
def scan_page(token):
    with get_db() as db:
        room = db.execute("SELECT r.*, s.name AS school_name, s.logo_url FROM rooms r JOIN schools s ON r.school_id=s.id WHERE r.qr_token=?", (token,)).fetchone()
        if not room:
            return render_template("scan_error.html", message="Invalid QR code.")

        sid     = room["school_id"]
        now     = datetime.now()
        now_str = now.strftime("%H:%M")
        date    = now.strftime("%Y-%m-%d")
        dow     = now.strftime("%A").upper()[:3]

        teachers = db.execute("SELECT * FROM teachers WHERE school_id=? AND active=1 ORDER BY surname,name", (sid,)).fetchall()
        period   = db.execute("SELECT * FROM periods WHERE school_id=? AND start_time<=? AND end_time>=? AND is_break=0 ORDER BY start_time LIMIT 1", (sid,now_str,now_str)).fetchone()
        if not period:
            period = db.execute("SELECT * FROM periods WHERE school_id=? AND start_time>? AND is_break=0 ORDER BY start_time LIMIT 1", (sid,now_str)).fetchone()

        scheduled = None
        if period:
            scheduled = db.execute("""SELECT t.*, tt.subject FROM timetable tt
                JOIN teachers t ON tt.teacher_id=t.id
                WHERE tt.school_id=? AND tt.room_id=? AND tt.period_id=? AND tt.day_of_week=?
            """, (sid, room["id"], period["id"], dow)).fetchone()

        teacher_states = {}
        for t in teachers:
            rec = db.execute("SELECT * FROM attendance WHERE school_id=? AND teacher_id=? AND period_id=? AND date=?",
                             (sid, t["id"], period["id"] if period else -1, date)).fetchone() if period else None
            if not rec:           teacher_states[t["id"]] = "NONE"
            elif not rec["scan_out_time"]: teacher_states[t["id"]] = "SCANNED_IN"
            else:                 teacher_states[t["id"]] = "COMPLETED"

    return render_template("scan.html",
        room=room, teachers=teachers, period=period,
        teacher_states=teacher_states, scheduled=scheduled,
        token=token, now_str=now_str,
        today=now.strftime("%A, %d %B %Y"))

@app.route("/scan/<token>/action", methods=["POST"])
def scan_action(token):
    with get_db() as db:
        room = db.execute("SELECT r.*, s.name AS school_name FROM rooms r JOIN schools s ON r.school_id=s.id WHERE r.qr_token=?", (token,)).fetchone()
        if not room:
            return jsonify({"success": False, "message": "Invalid QR code."})

        sid        = room["school_id"]
        teacher_id = request.form.get("teacher_id","").strip()
        action     = request.form.get("action","in")

        if not teacher_id:
            return jsonify({"success": False, "message": "Please select your name."})

        teacher = db.execute("SELECT * FROM teachers WHERE id=? AND school_id=?", (teacher_id, sid)).fetchone()
        if not teacher:
            return jsonify({"success": False, "message": "Teacher not found."})

        now     = datetime.now()
        now_str = now.strftime("%H:%M")
        date    = now.strftime("%Y-%m-%d")
        dow     = now.strftime("%A").upper()[:3]
        now_m   = _time_to_mins(now_str)

        period = db.execute("SELECT * FROM periods WHERE school_id=? AND start_time<=? AND end_time>=? ORDER BY start_time LIMIT 1", (sid,now_str,now_str)).fetchone()
        if not period:
            period = db.execute("SELECT * FROM periods WHERE school_id=? AND start_time>? AND is_break=0 ORDER BY start_time LIMIT 1", (sid,now_str)).fetchone()

        # ── SCAN IN ──────────────────────────────────────────────────────────
        if action == "in":
            if period:
                existing = db.execute("SELECT * FROM attendance WHERE school_id=? AND teacher_id=? AND period_id=? AND date=?",
                                      (sid,teacher_id,period["id"],date)).fetchone()
                if existing:
                    msg = "Already completed." if existing["scan_out_time"] else "Already checked in — scan out when you leave."
                    return jsonify({"success": False, "message": msg})

            slot        = None
            in_status   = "UNSCHEDULED"
            mins_late   = 0
            sched_start = sched_end = None

            if period:
                slot = db.execute("SELECT * FROM timetable WHERE school_id=? AND teacher_id=? AND room_id=? AND period_id=? AND day_of_week=?",
                                  (sid,teacher_id,room["id"],period["id"],dow)).fetchone()
                sched_start = period["start_time"]
                sched_end   = period["end_time"]
                mins_late   = now_m - _time_to_mins(sched_start)
                if slot:
                    in_status = "EARLY" if mins_late <= -GRACE_MINUTES else "ON_TIME" if mins_late <= GRACE_MINUTES else "LATE"
                else:
                    in_status = "UNSCHEDULED"

            plen = (_time_to_mins(period["end_time"]) - _time_to_mins(period["start_time"])) if period else None

            db.execute("""INSERT INTO attendance
                (school_id,teacher_id,room_id,period_id,timetable_id,date,day_of_week,
                 scan_in_time,scheduled_start,scheduled_end,in_status,out_status,minutes_late,period_length)
                VALUES(?,?,?,?,?,?,?,?,?,?,?,'PRESENT',?,?)""",
                (sid,teacher_id,room["id"],
                 period["id"] if period else None,
                 slot["id"]   if slot   else None,
                 date,dow,now_str,sched_start,sched_end,in_status,max(0,mins_late),plen))
            db.commit()

            msgs = {
                "EARLY":       ("⏰ Checked In Early!", f"Arrived {abs(mins_late)} min early.", "success"),
                "ON_TIME":     ("✅ Checked In On Time!", f"Signed in at {now_str}.", "success"),
                "LATE":        ("⚠️ Checked In Late", f"{mins_late} min late for {period['name'] if period else 'class'}.", "warning"),
                "UNSCHEDULED": ("📋 Checked In", f"Signed in at {now_str}. No scheduled class found.", "info"),
            }
            title, msg, kind = msgs.get(in_status, ("Recorded","Signed in.","info"))
            return jsonify({"success":True,"action":"in","status":in_status,
                            "title":title,"message":msg,"kind":kind,
                            "teacher":f"{teacher['name']} {teacher['surname']}",
                            "time":now_str,"period":period["name"] if period else "—"})

        # ── SCAN OUT ─────────────────────────────────────────────────────────
        elif action == "out":
            rec = db.execute("""SELECT * FROM attendance
                WHERE school_id=? AND teacher_id=? AND date=? AND scan_out_time IS NULL
                ORDER BY scan_in_time DESC LIMIT 1""", (sid,teacher_id,date)).fetchone()
            if not rec:
                return jsonify({"success":False,"message":"No active check-in found. Please scan in first."})

            dur        = now_m - _time_to_mins(rec["scan_in_time"])
            out_status = "COMPLETED"
            if rec["scheduled_end"]:
                end_m = _time_to_mins(rec["scheduled_end"])
                if now_m < end_m - EARLY_OUT_MINUTES:
                    out_status = "LEFT_EARLY"
                    mins_early = end_m - now_m

            db.execute("UPDATE attendance SET scan_out_time=?,out_status=?,duration_mins=? WHERE id=?",
                       (now_str, out_status, dur, rec["id"]))
            db.commit()

            pname = period["name"] if period else "—"
            if out_status == "LEFT_EARLY":
                title = "⚠️ Left Early"
                msg   = f"Left {end_m-now_m} min before end of {pname}. Time in room: {dur} min."
                kind  = "warning"
            else:
                title = "✅ Checked Out"
                msg   = f"Well done! You taught for {dur} minutes."
                kind  = "success"

            return jsonify({"success":True,"action":"out","status":out_status,
                            "title":title,"message":msg,"kind":kind,
                            "teacher":f"{teacher['name']} {teacher['surname']}",
                            "time_in":rec["scan_in_time"],"time_out":now_str,
                            "duration":dur,"period":pname})

    return jsonify({"success":False,"message":"Unknown action."})

# =============================================================================
# SUPER ADMIN
# =============================================================================

@app.route("/super/login", methods=["GET","POST"])
def super_login():
    if request.method == "POST":
        pw = _hash(request.form.get("password",""))
        with get_db() as db:
            user = db.execute("SELECT * FROM super_admins WHERE username=? AND password=?",
                              (request.form.get("username","").strip(), pw)).fetchone()
        if user:
            session["super_logged_in"] = True
            session["super_user"]      = user["username"]
            return redirect(url_for("super_dashboard"))
        flash("Invalid credentials", "error")
    return render_template("super_login.html")

@app.route("/super/logout")
def super_logout():
    session.clear()
    return redirect(url_for("super_login"))

@app.route("/super")
@super_required
def super_dashboard():
    with get_db() as db:
        total_schools  = db.execute("SELECT COUNT(*) FROM schools").fetchone()[0]
        active_schools = db.execute("SELECT COUNT(*) FROM schools WHERE status='active'").fetchone()[0]
        trial_schools  = db.execute("SELECT COUNT(*) FROM schools WHERE status='trial'").fetchone()[0]
        waiver_pending = db.execute("SELECT COUNT(*) FROM schools WHERE fee_waiver=2").fetchone()[0]
        total_teachers = db.execute("SELECT COUNT(*) FROM teachers WHERE active=1").fetchone()[0]
        total_scans    = db.execute("SELECT COUNT(*) FROM attendance").fetchone()[0]
        schools = db.execute("""
            SELECT s.*,
                   (SELECT COUNT(*) FROM teachers WHERE school_id=s.id AND active=1) AS teacher_count,
                   (SELECT COUNT(*) FROM attendance WHERE school_id=s.id AND date=?) AS scans_today
            FROM schools s ORDER BY s.created_at DESC
        """, (datetime.now().strftime("%Y-%m-%d"),)).fetchall()
        codes = db.execute("""
            SELECT ac.*, s.name AS used_by_school
            FROM access_codes ac
            LEFT JOIN schools s ON ac.used_by=s.id
            ORDER BY ac.created_at DESC LIMIT 30
        """).fetchall()
    return render_template("super_dashboard.html",
        total_schools=total_schools, active_schools=active_schools,
        trial_schools=trial_schools, waiver_pending=waiver_pending,
        total_teachers=total_teachers, total_scans=total_scans,
        schools=schools, codes=codes)

@app.route("/super/generate-code", methods=["POST"])
@super_required
def generate_code():
    plan       = request.form.get("plan","basic")
    months     = int(request.form.get("months",12))
    fee_waiver = 1 if request.form.get("fee_waiver") else 0
    notes      = request.form.get("notes","").strip()
    count      = int(request.form.get("count",1))
    with get_db() as db:
        codes = []
        for _ in range(min(count, 20)):
            code = _generate_code()
            db.execute("INSERT INTO access_codes(code,plan,months,fee_waiver,notes) VALUES(?,?,?,?,?)",
                       (code, plan, months, fee_waiver, notes))
            codes.append(code)
        db.commit()
    flash(f"Generated {len(codes)} code(s): " + " | ".join(codes), "success")
    return redirect(url_for("super_dashboard"))

@app.route("/super/school/<int:sid>/action", methods=["POST"])
@super_required
def super_school_action(sid):
    action = request.form.get("action")
    with get_db() as db:
        if action == "activate":
            expires = (datetime.now() + timedelta(days=365)).strftime("%Y-%m-%d")
            db.execute("UPDATE schools SET status='active', plan='premium', plan_expires=? WHERE id=?",
                       (expires, sid))
            flash("School activated for 1 year", "success")
        elif action == "suspend":
            db.execute("UPDATE schools SET status='suspended' WHERE id=?", (sid,))
            flash("School suspended", "success")
        elif action == "approve_waiver":
            db.execute("UPDATE schools SET fee_waiver=1, status='active' WHERE id=?", (sid,))
            flash("Fee waiver approved", "success")
        elif action == "deny_waiver":
            db.execute("UPDATE schools SET fee_waiver=0 WHERE id=?", (sid,))
            flash("Fee waiver denied", "success")
        elif action == "delete":
            db.execute("DELETE FROM schools WHERE id=?", (sid,))
            flash("School deleted", "success")
        db.commit()
    return redirect(url_for("super_dashboard"))

@app.route("/super/stats")
@super_required
def super_stats():
    with get_db() as db:
        monthly = db.execute("""
            SELECT strftime('%Y-%m', date) AS month,
                   COUNT(*) AS scans,
                   SUM(CASE WHEN in_status='LATE' THEN 1 ELSE 0 END) AS late,
                   SUM(CASE WHEN out_status='LEFT_EARLY' THEN 1 ELSE 0 END) AS left_early
            FROM attendance
            GROUP BY month ORDER BY month DESC LIMIT 12
        """).fetchall()
        top_schools = db.execute("""
            SELECT s.name, COUNT(*) AS scans
            FROM attendance a JOIN schools s ON a.school_id=s.id
            GROUP BY s.id ORDER BY scans DESC LIMIT 10
        """).fetchall()
    return render_template("super_stats.html", monthly=monthly, top_schools=top_schools)

# ── Error pages ───────────────────────────────────────────────────────────────
@app.errorhandler(404)
def not_found(e):
    return render_template("scan_error.html", message="Page not found."), 404

if __name__ == "__main__":
    init_db()
    app.run(host="0.0.0.0", port=5000, debug=False)
